#!/bin/sh

pactl load-module module-null-sink sink_name=Virtual1
pactl load-module module-loopback source=alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback sink=Virtual1 
pactl load-module module-loopback source=Virtual1.monitor sink=alsa_output.pci-0000_00_1f.3.analog-stereo
