#!/bin/sh

artist=$(cmus-remote -Q |
		grep --text '^tag artist' |
		sed '/^tag artistsort/d' |
		awk '{gsub("tag artist ", "");print}')
title=$(cmus-remote -Q  |
		grep --text '^tag title' |
		sed -e 's/tag title //' |
		awk '{gsub("tag title ", "");print}')


# Verbose Output

test "$1" = "verbose" &&
	echo "$(checkSpace v)" &&
	echo &&
	echo "$(checkBattery) $(cat /sys/class/power_supply/BAT0/status)" &&
	echo &&
	echo "$(checkIptables)" &&
	echo "$(checkWifi)" &&
	echo "$(checkVPN)" &&
	echo &&
	echo "$(checkUsage)" &&
	echo "$(checkTemp)" &&
	echo &&
        echo "$(date +%c)" &&
	echo &&
	echo "$title, $artist" &&
	echo &&
       	exit 0  

# Simple Output

echo "$(checkSpace) | $(checkBattery) | $(checkWifi raw) | $(checkVPN notify) |  $(date +%R:%S)"
