#!/bin/sh

artist=$(cmus-remote -Q |
		grep --text '^tag artist' |
		sed '/^tag artistsort/d' |
		awk '{gsub("tag artist ", "");print}')
title=$(cmus-remote -Q  |
		grep --text '^tag title' |
		sed -e 's/tag title //' |
		awk '{gsub("tag title ", "");print}')

audioDevice=$(pactl list sinks | grep '^[[:space:]]Description:' | head -n $(( 1 + 1 )) | tail -n 1 | sed "s/^[ \t]*//" | sed 's/Description: //g')
test -z $(pactl list sinks | grep '^[[:space:]]Name:' | head -n $(( 1 + 1 )) | tail -n 1 | grep bluez) || blue=" "

# Verbose Output

test "$1" = "verbose" &&
	echo "$(checkSpace v)" &&
	echo &&
	echo "$(checkBattery) $(cat /sys/class/power_supply/BAT0/status)" &&
	echo &&
	echo "$(checkIptables)" &&
	echo "$(checkWifi)" &&
	echo "$(checkVPN)" &&
	echo &&
	echo "$(checkUsage)" &&
	echo "$(checkTemp)" &&
	echo &&
        echo "$(date +%c)" &&
	echo &&
	echo "$title, $artist" &&
	echo &&
       	exit 0  

# Simple Output

echo "$(checkSpace) | $(checkBattery) | $(checkWifi raw) | $(checkTime) | $blue$(checkVolume)"
