#!/bin/sh

# Verbose Output

test "$1" = "verbose" &&
	echo "$(checkSpace v)" &&
	echo &&
	echo "$(checkBattery) $(cat /sys/class/power_supply/BAT0/status)" &&
	echo &&
	echo "$(checkWifi)" &&
	echo "$(checkVPN)" &&
	echo &&
	echo "$(checkUsage)" &&
	echo "$(checkTemp)" &&
	echo &&
        echo "$(date +%c)" &&
	echo &&
       	exit 0  

# Simple Output

echo "$(checkSpace) | $(checkBattery) | $(checkTemp) | $(checkWifiVPN) | $(date +%R:%S) "
