#! /bin/sh

bspc subscribe | while read -r line; do
    node_num=$(bspc query --nodes --desktop | wc -l)
    if [ "$node_num" != "0" ]; then
	xwallpaper --zoom ~/media/images/bkg/paintedLandscape.png
    else
	xwallpaper --zoom ~/media/images/bkg/paintedLandscapeBlur.png
    fi
done;

    
