#!/bin/bash

oldNodes="$(bspc query -N)"
spotify &
sleep 0.5s
newNodes="$(bspc query -N)"

new="$(diff <(echo "$oldNodes") <(echo "$newNodes") | awk '{print $2}')"

new1="$(echo $newRaw | awk '{print $1}')"
bspc node $new1 -d ^7
