#!/bin/sh

connectionName="$(nmcli c show --active | grep -Eo '^[^ ]+' | grep -v NAME | head -1)"
active="$(nmcli c show --active | grep tun | head -1)"

test -n "$active" && echo " Connected to VPN $connectionName" || echo " Disconnected from VPN"
