#!/bin/sh

test -z "$(cd ~/.configbackup/ && git status --porcelain --ignore-submodules)" || notify-send " Config Backup Dirty"	
sleep 10s
notify-send "$(/home/beta/.apps/toofoo/main.sh)"
sleep 50s
~/.bin/checkPackages
