#!/bin/sh

export DISPLAY=:0

/home/beta/.bin/checkWifi raw>/dev/null || exit 3

/usr/bin/notify-send " Syncing Repositories"

test -z "$(xbps-install -Sun)" || /usr/bin/notify-send " Updates are available" && /usr/bin/notify-send " No updates available"
