#!/bin/sh

active=$(nmcli | grep -v -E 'interface|p2p' | grep 'wlp58s0' | grep -v 'disconnected' | grep 'connected')

if [ "$1" = "raw" ]; then
	test -n "$active" || exit 1
fi

test -n "$active" && echo "  New Connection: $(nmcli c show --active | grep wifi | awk '{print $1}')" || echo " Disconnected from Network"
