#!/bin/sh

full=$(acpi -b | grep Full)
charge="$(cat /sys/class/power_supply/BAT0/capacity)"

generateLevel(){

	test "$charge" -lt 11 && level="" && return 0
	test "$charge" -lt 21 && level="" && return 0
	test "$charge" -lt 31 && level="" && return 0
	test "$charge" -lt 41 && level="" && return 0
	test "$charge" -lt 51 && level="" && return 0
	test "$charge" -lt 61 && level="" && return 0
	test "$charge" -lt 71 && level="" && return 0
	test "$charge" -lt 81 && level="" && return 0
	test "$charge" -lt 91 && level="" && return 0
	test "$charge" -lt 101 && level="" && return 0
}

generateLevel

if [ -n "$full" ];then
       	echo "⚡100%" 
elif [ "$charge" = "100" ];then
	echo " $charge%"
else
	test "$(cat /sys/class/power_supply/BAT0/status)" = "Discharging" && echo "$level $(acpi -b | grep -E -o '[0-9][0-9]?%')" || echo " $(acpi -b | grep -E -o '[0-9][0-9]?%')" 
fi
