#!/bin/bash

test "$1" = "v" &&
	echo  " $(df -H --output=avail,pcent /home/beta | tail -n 1)" &&
	echo  " $(df -H --output=avail,pcent / | tail -n 1)" &&
	exit 0

echo -n 🏢 $(df -h --output=avail /home/beta | tail -n 1)
echo -n " "
echo -n 💽  $(df -h --output=avail / | tail -n 1)
