#!/bin/sh

notify-send "Yo! Don't forget to start your dmesg monitoring, fool!"

test -z "$(cd ~/.configbackup/ && git status --porcelain --ignore-submodules)" || notify-send " Config Backup Dirty"	
sleep 30s
~/.bin/checkPackages
sleep 3s
~/.bin/checkRSS
