#!/bin/sh

#  
activewifi=$(nmcli | grep -v -E 'interface|p2p' | grep 'wlp58s0' | grep -v 'disconnected' | grep 'connected')
activevpn="$(nmcli c show --active | grep tun | head -1)"

if [ -n "$activewifi" ]; then
	test -n "$activevpn" && echo "$(nmcli c show --active | grep wifi | awk '{print $1;}')" && exit 0
	echo " $(nmcli c show --active | grep wifi | awk '{print $1;}')"
else
	echo "DOWN"
fi
