#!/bin/bash

#These are the variables you should change.

dirpath=/home/beta/.configbackup/
dirarr=(/home/beta/.config)
filearr=(/home/beta/.Xresources /home/beta/.vim/vimrc home/beta/.zshenv /home/beta/.apps/st-0.8.2/config.h)

#Generate Directory Name (Today's date e.g. 11.01.20)

dir="$(date '+%d.%m.%y')"

# Create Directory

test -d $dirpath$dir && echo "Directory exists, copying to it" || mkdir $dirpath$dir

#Copy directories

for i in "${dirarr[@]}"
do
    cp -r $i $dirpath$dir
done

echo

#Copy config files

for i in "${filearr[@]}"
do
    cp $i $dirpath$dir
done

# Compress folder

cd $dirpath
tar -zcvf $dir.tar.gz $dir

# Cleanup

rm -rf $dirpath$dir

cd $dirpath
git add . &>/dev/null
git -c commit.gpgsign=false commit -m "$dir" &>/dev/null
git push &>/dev/null
