#!/bin/bash

shortname=(dunst vim rifle ranger colours urxvt bspwm sxhkd st dwm zsh cmus newsboat zathura url lf polybar sxiv khal mutt offlineimap)

#THIS MUST BE IN THE SAME ORDER AS THE SHORTNAME ARRAY

namepath=(\
       	~/.config/dunst/dunstrc\
       	~/.vim/vimrc\
       	~/.config/ranger/rifle.conf\
       	~/.config/ranger/rc.conf\
       	~/.config/polybar/colors.ini\
       	~/.Xresources\
       	~/.config/bspwm/bspwmrc\
       	~/.config/sxhkd/sxhkdrc\
       	~/.apps/st-0.8.2/config.h\
       	~/.apps/dwm-6.2/config.h\
       	~/.config/zsh/.zshrc\
	~/.config/cmus/rc\
	~/.config/newsboat/config\
	~/.config/zathura/zathurarc\
	~/.config/newsboat/urls\
	~/.config/lf/lfrc\
	~/.config/polybar/config\
	~/.apps/sxiv/config.h\
	~/.config/khal/config\
	~/.config/mutt/muttrc\
	~/.config/offlineimap/config
)

attempts=0
found=false

test -z $EDITOR && EDITOR=nano

while [ "$attempts" -le "${#namepath[@]}" ]
do
	if [ "$1" = "${shortname[$attempts]}" ]
	then
		found=true
		$EDITOR "${namepath[$attempts]}"		
	fi
	attempts=$(( attempts + 1 ))
done

test $found = true || exit 1
