#!/bin/sh

export DISPLAY=:0.0 

test -z "$(cat /sys/class/power_supply/BAT0/status | grep "Charging")" && test $(cat /sys/class/power_supply/BAT0/capacity) -lt 20 && /usr/bin/notify-send " Battery Critically Low! $(cat /sys/class/power_supply/BAT0/capacity)% Remaining"
