#!/bin/sh

case $1 in
	double)
		xrandr --output eDP1 --primary
		xrandr --output DP1 --above eDP1
		xrandr --output eDP1 --primary
		$HOME/.bin/bspwmMonitorCalibrate
		echo "🖥 Connecting to Monitor DP1"
	;;
	single)
		echo "🖥 Resetting to main screen"
		for Line in $(bspc query -m DP1 --nodes)
		do
			echo "Moving $(xprop -id $Line WM_NAME 2>/dev/null | sed 's/^.*=//g' | sed 's/\"//g' | sed 's/^ //g')"
			bspc node $Line -d 1
		done
		xrandr --output DP1 --off
		xrandr --output eDP1 --auto
	;;
esac

setxkbmap gb
