#!/bin/sh

w1="⚪"
w2="⚪"
w3="⚪"
w4="💬"
w5="🔧"
w6="🔧"
w7="🎧"
w8="🖥"
w9="🖥"

case $1 in
	double)
		xrandr --output eDP1 --auto
		xrandr --output DP1 --auto
		xrandr --output DP1 --primary --above eDP1
		echo "🖥 Connecting to Monitor DP1"
	;;
	single)
		echo "🖥 Resetting to main screen"
		for Line in $(bspc query -m DP1 --nodes)
		do
			echo "Moving $(xprop -id $Line WM_NAME 2>/dev/null | sed 's/^.*=//g' | sed 's/\"//g' | sed 's/^ //g')"
			bspc node $Line -d $w1
		done
		bspc monitor DP1 --remove
		xrandr --output DP1 --off
		xrandr --output eDP1 --auto
	;;
esac

bspc monitor eDP1 -d $w1 $w2 $w3 $w4 $w5 $w6 $w7
test "$(xrandr | grep 1920x1080 | grep "*" | wc -l)" = "2" && bspc monitor DP1 -d $w8 $w9 && bspc monitor DP1 --swap "^2"
