#!/bin/sh

xsel -bc
cmus-remote -s
notify-send "DUNST_COMMAND_PAUSE"

i3lock -ent --pass-media-keys -i ~/media/images/bkg/lockBackground.png --insidecolor=00000000 --ringcolor=000000ff --keyhlcolor=ffffffff --bshlcolor=ffffffff --separatorcolor=000000ff --linecolor=000000ff --insidevercolor=00000000 --ringvercolor=ffffffff --wrongtext="" --veriftext="" --noinputtext="" && notify-send "DUNST_COMMAND_RESUME"
