#!/bin/sh

export DISPLAY=:0.0

cmus-remote -U
playerctl pause -a & 
dunstctl set-paused true

i3lock -ent --pass-media-keys -i ~/media/images/bkg/lockBackground.png --inside-color=00000000 --ring-color=000000ff --keyhl-color=ffffffff --bshl-color=ffffffff --separator-color=000000ff --line-color=000000ff --insidever-color=00000000 --ringver-color=0099ffff --wrong-text="" --verif-text="" --noinput-text="" --insidewrong-color=00000000 --ringwrong-color=900000ff && dunstctl set-paused false
