#!/bin/sh

export DISPLAY=:0.0 

capacity="$(cat /sys/class/power_supply/BAT0/capacity)"

test "$1" = "ac" && /usr/bin/notify-send " Charging on AC"
test "$1" = "bat" && /usr/bin/notify-send "$(/home/beta/.bin/checkBattery | awk '{print $1}') On Battery Power"

test -n "$(grep "Charging" /sys/class/power_supply/BAT0/status)" && 
	test $(xbacklight | cut -d '.' -f1) -lt 101 &&
	xbacklight = 100 &&
	exit 0

if [ $capacity -lt 100 ] && [ $capacity -gt 0 ]; then
	newLight=$((capacity + 10))
	echo $newLight
	xbacklight -set "$newLight"
fi

test -z "$(grep "Discharging" /sys/class/power_supply/BAT0/status)" && exit 2

if [ "$capacity" -lt 26 ]; then

	if [ "$capacity" -lt 11 ];then 
		/usr/bin/notify-send --urgency=critical " Battery Critically Low! $capacity% Remaining."
		exit 0
	fi

	/usr/bin/notify-send --urgency=critical " Battery Low! $capacity% Remaining"

fi
