#!/bin/sh

while true; do

	oldStatus=$(checkWifi)
	oldStatusVPN=$(checkVPN)
	sleep 5s
	newStatus=$(checkWifi)
	newStatusVPN=$(checkVPN)

	test "$oldStatus" != "$newStatus" && notify-send "$(checkWifi)"
	test "$oldStatusVPN" != "$newStatusVPN" && notify-send "$(checkVPN)"
	
done 
