#!/bin/sh

export DISPLAY=:0.0

case $1 in
	vpnhere)	sudo -u beta /usr/bin/dunstify -r 3000 " VPN $(/home/beta/.bin/checkVPN raw | awk '{ print $2  }') Connected" 	;;
	vpngone)	sudo -u beta /usr/bin/dunstify -r 3001 " VPN Disconnected"		;;
esac
