#!/bin/sh

export DISPLAY=:0.0/
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
export XAUTHORITY=/home/beta/.Xauthority

case $1 in
	vpnhere)	dunstify -r 3000 " VPN $(/home/beta/.bin/checkVPN raw | awk '{ print $2  }') Connected" 	;;
	vpngone)	dunstify -r 3001 " VPN Disconnected"		;;
esac
