#!/bin/sh

test -z "$2" || toolOpenFed="$2" && pathInput="$1"
test -z "$(echo $2 | sed 's/ //g')" && pathInput="$1"

echo "$pathInput"

fileinfo="$(file --mime-type -b $pathInput)"

case $fileinfo in
	application/pdf) toolOpen="zathura";;
	text/plain) toolOpen="st -e vim";;
	text/x-tex) toolOpen="st -e vim";;
	application/vnd.openxmlformats-officedocument.wordprocessingml.document) toolOpen="libreoffice";;
	*) toolOpen="fail" ;;
esac

if [ $(echo "$pathInput" | grep "^https://") ]
then
	toolOpen="firefox"
fi

if [ $(echo "$pathInput" | grep "https://www.youtube.com") ] || [ $(echo "$pathInput" | grep "https://youtube.com") ]
then
	toolOpen="mpv"
fi

echo "$toolOpen"
test -n "$toolOpenFed" && toolOpen="$toolOpenFed"
test "$toolOpen" = "fail" && notify-send "❌ Could not find program to open with" "$pathInput" && exit 1

$toolOpen "$pathInput" &>/dev/null &
