#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar
polybar -c ~/.config/polybar/config.ini main &

external=$(xrandr --query | grep 'DP1 connected 1920')
echo $external
if [[ $external ]]; then
    echo "connected"
    polybar -c ~/.config/polybar/config.ini main2 &
fi
