#!/bin/sh

units="$(printf "lbskg\nkglbs\nmileskm\nkmmiles" | dmenu -fn "Source Code Pro For Powerline" -p "Units:")"
inputNum="$(printf "" | dmenu -fn "Source Code Pro for Powerline" -p "Value:")"

case $units in
	lbskg) output="$(echo "$inputNum * 0.45359237" | bc -l)"		;;
	kglbs) output="$(echo "$inputNum * 2.2046226218488" | bc -l)"		;;
	kmmiles) output="$(echo "$inputNum * 0.62137119223733" | bc -l)"		;;
	mileskm) output="$(echo "$inputNum * 1.609344" | bc -l)"		;;
	*) output="No valid input"				;;
esac

echo "↪ $output" 
