#!/bin/sh


case $1 in
	up)
		amixer sset Master 2%+
	;;
	down)
		amixer sset Master 2%-
	;;
	toggle)
		amixer set Master toggle
		test "$(amixer | grep "Playback" | grep "\[on\]")" && dunstify -r 1003 "🔊 Unmuted" || dunstify -r 1003 "🔇 Muted"
	;;
esac
