#!/bin/sh


case $1 in
	up)
		amixer sset Master 2%+
	;;
	down)
		amixer sset Master 2%-
	;;
	toggle)
		amixer set Master toggle
		test "$(amixer | grep "Playback" | grep "\[on\]")" && dunstify -r 1003 "🔊 Unmuted" || dunstify -r 1003 "🔇 Muted"
	;;
esac

[ -z "$(find /tmp -maxdepth 1 -name "polybar*")" ] && \
polybar level & \
while [ -z "$(find /tmp -maxdepth 1 -name "polybar*")" ]; do sleep 1; done

# Replace if already running
running=$(pidof -x $0)

while [ "$(echo $running| wc -w)" -gt "1" ]; do
	oldprocess=$(echo $running| rev| cut -d' ' -f1| rev)
	kill $oldprocess
	running=$(pidof -x $0)
done

polybar-msg cmd show
xdo raise -a "polybar-level_eDP1"

sleep 0.8
polybar-msg cmd hide

