#!/bin/sh


case $1 in
	up)
		amixer sset Master 10%+
		symbol=
	;;
	down)
		amixer sset Master 10%-
		symbol=
	;;
esac

rawvol=$(amixer sget Master)
echo $rawvol
vol=$(echo $rawvol | awk -F"[][]" '/dB/ { print $2 }')
echo $vol
