#!/bin/sh

selection="$(printf "$(nmcli c show | grep -Eo '^[^ ]+' | grep -v NAME)" | dmenu -i -l 30 -fn "Source Code Pro For Powerline" -p "Bring $1:")"

test "$1" = "up" && action="🌐 Connecting to" || action="❌ Disconnecting from"

notify-send "$action $selection" && nmcli c $1 $selection || notify-send "🛑 Connection Failed"
