#!/bin/bash

IFS=$'\r\n' GLOBIGNORE='*' command eval  'XYZ=($(cat /home/beta/packages))'

echo "${XYZ[5]}"

for i in "${XYZ[@]}"
do
	echo $i
	package=$(echo $i | awk '{print $2}')
	echo $package
	xbps-install -Sy $package
done
