#!/bin/sh

priceDataRaw=$(curl -s https://rate.sx/xlm)
priceDataSplit=$(echo $priceDataRaw | cut -d "/" -f9)
percentage=$(echo $priceDataSplit | cut -d "(" -f2 | cut -d ")" -f1 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
changeInt=$(echo $priceDataSplit | cut -d " " -f2 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")

test $(echo $changeInt | grep "+") && changeInt="<span color='#33cc33'>$changeInt</span>" || changeInt="<span color='#ff3300'>$changeInt</span>"

test $(echo $percentage | grep "+") && percentage="<span color='#33cc33'>$percentage</span>" || percentage="<span color='#ff3300'>$percentage</span>"

echo "$ $(curl -s rate.sx | grep XLM | cut -d " " -f9 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")"
echo "$changeInt"
echo "$percentage"
